
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kundu
 */
import java.util.Calendar;
import java.sql.*;
public class parking_facility extends javax.swing.JFrame {
    String str,str1;
    int a,b,c,d,ho,mi;
    int vn,am;
   int id; 
    String name,ti,to;
   static String cols[]={"Pid","Name","Vehicle_No","Time_of_entry","T_of_exit","hour_of_entry","min_of_entry","hour_of_exit","min_of_exit","cost"};
    static String rows[][];
    DefaultTableModel tm= new DefaultTableModel(rows,cols);
    
   

    /**
     * Creates new form parking_facility
     */
    public parking_facility() {
 
        initComponents();
  
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
       
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JLayeredPane();
        p1l1 = new javax.swing.JLabel();
        p1l2 = new javax.swing.JLabel();
        p1b1 = new javax.swing.JButton();
        p1b2 = new javax.swing.JButton();
        p1b3 = new javax.swing.JButton();
        p2 = new javax.swing.JLayeredPane();
        p2l1 = new javax.swing.JLabel();
        p2l2 = new javax.swing.JLabel();
        p2t1 = new javax.swing.JTextField();
        p2l3 = new javax.swing.JLabel();
        p2t2 = new javax.swing.JTextField();
        p2l4 = new javax.swing.JLabel();
        p2b1 = new javax.swing.JButton();
        p2l5 = new javax.swing.JLabel();
        p2l6 = new javax.swing.JLabel();
        p2b2 = new javax.swing.JButton();
        p2b3 = new javax.swing.JButton();
        p2l7 = new javax.swing.JLabel();
        p2l8 = new javax.swing.JLabel();
        p2l9 = new javax.swing.JLabel();
        p2b4 = new javax.swing.JButton();
        p2b5 = new javax.swing.JButton();
        p3 = new javax.swing.JLayeredPane();
        p3l1 = new javax.swing.JLabel();
        p3t1 = new javax.swing.JTextField();
        p3l2 = new javax.swing.JLabel();
        p3b1 = new javax.swing.JButton();
        p3l3 = new javax.swing.JLabel();
        p3l4 = new javax.swing.JLabel();
        p3l5 = new javax.swing.JLabel();
        p3l6 = new javax.swing.JLabel();
        p3l7 = new javax.swing.JLabel();
        p3l8 = new javax.swing.JLabel();
        p3l9 = new javax.swing.JLabel();
        p3l10 = new javax.swing.JLabel();
        p3l11 = new javax.swing.JLabel();
        p3l12 = new javax.swing.JLabel();
        p3l13 = new javax.swing.JLabel();
        p3b2 = new javax.swing.JButton();
        p3b3 = new javax.swing.JButton();
        p3b4 = new javax.swing.JButton();
        p3b5 = new javax.swing.JButton();
        p4 = new javax.swing.JLayeredPane();
        p4l1 = new javax.swing.JLabel();
        p4l2 = new javax.swing.JLabel();
        p4l3 = new javax.swing.JLabel();
        p4t1 = new javax.swing.JTextField();
        p4b1 = new javax.swing.JButton();
        p4b2 = new javax.swing.JButton();
        p4b3 = new javax.swing.JButton();
        p4b4 = new javax.swing.JButton();
        p4p1 = new javax.swing.JPasswordField();
        p5 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        b1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        p1l1.setBackground(new java.awt.Color(255, 255, 255));
        p1l1.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        p1l1.setForeground(new java.awt.Color(0, 204, 51));
        p1l1.setText("                WELCOME TO ");

        p1l2.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        p1l2.setForeground(new java.awt.Color(0, 255, 102));
        p1l2.setText("     STAR PARKING FACILITY");

        p1b1.setText("PARK");
        p1b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1b1ActionPerformed(evt);
            }
        });

        p1b2.setText("EXIT");
        p1b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1b2ActionPerformed(evt);
            }
        });

        p1b3.setText("HISTORY");
        p1b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1b3ActionPerformed(evt);
            }
        });

        p1.setLayer(p1l1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p1.setLayer(p1l2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p1.setLayer(p1b1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p1.setLayer(p1b2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p1.setLayer(p1b3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(p1b3))
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1l1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(p1b1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(210, 210, 210)
                                .addComponent(p1b2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(p1l2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addComponent(p1b3)
                .addGap(12, 12, 12)
                .addComponent(p1l1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p1l2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1b1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1b2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        p2l1.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        p2l1.setForeground(new java.awt.Color(51, 153, 255));
        p2l1.setText("PLEASE ENTER YOUR DETAILS");

        p2l2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p2l2.setText("NAME");

        p2t1.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N

        p2l3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p2l3.setText("VEHICLE NO.");

        p2t2.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N

        p2l4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p2l4.setText("TIME IN");

        p2b1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        p2b1.setForeground(new java.awt.Color(0, 204, 51));
        p2b1.setText("SUBMIT");
        p2b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2b1ActionPerformed(evt);
            }
        });

        p2l5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p2l5.setText("YOUR ID");

        p2l6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p2l6.setText("   ");

        p2b2.setText("BACK");
        p2b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2b2ActionPerformed(evt);
            }
        });

        p2b3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p2b3.setText("CORRECT");
        p2b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2b3ActionPerformed(evt);
            }
        });

        p2l7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p2l7.setText("jLabel1");

        p2l8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p2l8.setText("jLabel2");

        p2l9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p2l9.setText("jLabel3");

        p2b4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p2b4.setText("RESET");
        p2b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2b4ActionPerformed(evt);
            }
        });

        p2b5.setText("OK!!!!!");
        p2b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2b5ActionPerformed(evt);
            }
        });

        p2.setLayer(p2l1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2.setLayer(p2l2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2.setLayer(p2t1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2.setLayer(p2l3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2.setLayer(p2t2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2.setLayer(p2l4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2.setLayer(p2b1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2.setLayer(p2l5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2.setLayer(p2l6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2.setLayer(p2b2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2.setLayer(p2b3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2.setLayer(p2l7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2.setLayer(p2l8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2.setLayer(p2l9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2.setLayer(p2b4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2.setLayer(p2b5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(p2b2)
                        .addGap(41, 41, 41)
                        .addComponent(p2l1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(p2b5)
                            .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(p2Layout.createSequentialGroup()
                                    .addGap(239, 239, 239)
                                    .addComponent(p2b1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(p2Layout.createSequentialGroup()
                                    .addGap(149, 149, 149)
                                    .addComponent(p2b3))))
                        .addGap(73, 73, 73)
                        .addComponent(p2b4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p2Layout.createSequentialGroup()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(p2l4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p2l3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p2l2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(p2l5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(183, 183, 183)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p2t1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(p2t2)
                    .addComponent(p2l6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2l8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2l9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2l7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(p2l1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p2b2))
                .addGap(29, 29, 29)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2l5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2l6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2l2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2t1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2l7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(p2b5)
                .addGap(4, 4, 4)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2l3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2t2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2l8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2l4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2l9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2b3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2b4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(p2b1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        p3l1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        p3l1.setForeground(new java.awt.Color(255, 102, 102));
        p3l1.setText("       EXIT");

        p3t1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N

        p3l2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        p3l2.setText("     ENTER YOUR ID");

        p3b1.setForeground(new java.awt.Color(0, 204, 51));
        p3b1.setText("GO!!!!!");
        p3b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3b1ActionPerformed(evt);
            }
        });

        p3l3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p3l3.setText("NAME");

        p3l4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p3l4.setText("VEHIVLE NO.");

        p3l5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p3l5.setText("PARKING TIME");

        p3l6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p3l6.setForeground(new java.awt.Color(51, 51, 51));
        p3l6.setText("EXIT TIME");

        p3l7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p3l7.setText("AMOUNT TO BE PAID");

        p3l8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        p3l8.setForeground(new java.awt.Color(204, 204, 0));
        p3l8.setText("       THANK YOU FOR COMING");

        p3l9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N

        p3l10.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p3l10.setText("  ");

        p3l11.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p3l11.setText("   ");

        p3l12.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p3l12.setText("  ");

        p3l13.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p3l13.setText("   ");

        p3b2.setText("BACK");
        p3b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3b2ActionPerformed(evt);
            }
        });

        p3b3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        p3b3.setText("OK");
        p3b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3b3ActionPerformed(evt);
            }
        });

        p3b4.setText("BYE!!!");
        p3b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3b4ActionPerformed(evt);
            }
        });

        p3b5.setText("NOT YOUR ID");
        p3b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3b5ActionPerformed(evt);
            }
        });

        p3.setLayer(p3l1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3t1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3l2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3b1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3l3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3l4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3l5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3l6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3l7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3l8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3l9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3l10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3l11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3l12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3l13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3b2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3b3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3b4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p3.setLayer(p3b5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p3l7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p3l6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p3l5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p3l4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p3l3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(341, 341, 341)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p3l9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p3l10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p3l11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p3l12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p3l13, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(p3b5)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(p3b2)))
                        .addGap(129, 129, 129)
                        .addComponent(p3l1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p3Layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(p3l8, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p3Layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(p3t1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p3b4))
                            .addGroup(p3Layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(p3l2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p3Layout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p3b1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(p3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(p3b3)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(p3l1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addComponent(p3b2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p3b5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p3l3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p3l9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(p3l8, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3l4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3l10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p3l2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3l5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3l11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3t1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3b4))
                .addGap(20, 20, 20)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3l6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3l12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(p3b1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3l7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3l13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p3b3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        p4l1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        p4l1.setText("WELCOME TO PARKING HISTORY");

        p4l2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        p4l2.setText("USER");

        p4l3.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        p4l3.setText("PASSWORD");

        p4b1.setText("SHOW HISTORY");
        p4b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4b1ActionPerformed(evt);
            }
        });

        p4b2.setText("BACK");
        p4b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4b2ActionPerformed(evt);
            }
        });

        p4b3.setText("BACK");
        p4b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4b3ActionPerformed(evt);
            }
        });

        p4b4.setText("SUBMIT");
        p4b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4b4ActionPerformed(evt);
            }
        });

        p4.setLayer(p4l1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p4.setLayer(p4l2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p4.setLayer(p4l3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p4.setLayer(p4t1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p4.setLayer(p4b1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p4.setLayer(p4b2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p4.setLayer(p4b3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p4.setLayer(p4b4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p4.setLayer(p4p1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p4Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(p4Layout.createSequentialGroup()
                                .addComponent(p4l2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(p4b1))
                            .addGroup(p4Layout.createSequentialGroup()
                                .addComponent(p4l3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(p4b2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p4t1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(p4p1)))
                    .addGroup(p4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(p4l1))
                    .addGroup(p4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(p4b3))
                    .addGroup(p4Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(p4b4)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p4l1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4l2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4t1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4b1))
                .addGap(52, 52, 52)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4l3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4b2)
                    .addComponent(p4p1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(p4b4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(p4b3)
                .addContainerGap())
        );

        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jt1);

        b1.setText("back");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        p5.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p5.setLayer(b1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout p5Layout = new javax.swing.GroupLayout(p5);
        p5.setLayout(p5Layout);
        p5Layout.setHorizontalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(b1)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        p5Layout.setVerticalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b1)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(p2))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(p3))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(p2))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(p3))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p1b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1b3ActionPerformed
p1.setVisible(false);
p4b1.setVisible(false);
p4b2.setVisible(false);
p4.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_p1b3ActionPerformed

    private void p1b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1b1ActionPerformed
p1.setVisible(false);
p2t1.setText("");
p2t2.setText("");
p2b4.setVisible(false);
p2b5.setVisible(false);
p2l7.setVisible(false);
p2l8.setVisible(false);
p2l9.setVisible(false);
p2l5.setVisible(false);
p2l6.setVisible(false);
p2b3.setVisible(false);
p2l4.setVisible(false);
p2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_p1b1ActionPerformed

    private void p1b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1b2ActionPerformed
p1.setVisible(false);
p3t1.setText("");
p3l3.setVisible(false);
p3l4.setVisible(false);
p3l5.setVisible(false);
p3l6.setVisible(false);
p3l7.setVisible(false);
p3l8.setVisible(false);
p3l9.setVisible(false);
p3l10.setVisible(false);
p3l11.setVisible(false);
p3l12.setVisible(false);
p3l13.setVisible(false);
p3b3.setVisible(false);
p3b4.setVisible(false);
p3b5.setVisible(false);
p3.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_p1b2ActionPerformed

    private void p2b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2b2ActionPerformed
p2.setVisible(false);
p1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_p2b2ActionPerformed

    private void p3b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3b2ActionPerformed
p3.setVisible(false);
p3t1.setText("");
p1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_p3b2ActionPerformed

    private void p4b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4b3ActionPerformed
p4.setVisible(false);
p4t1.setText("");
p4p1.setText("");
p1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_p4b3ActionPerformed

    private void p3b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3b3ActionPerformed
p3l1.setVisible(false);
        p3l3.setVisible(false);
        p3t1.setText("");
p3b5.setVisible(false);
p3l4.setVisible(false);
p3l5.setVisible(false);
p3l6.setVisible(false);
p3l7.setVisible(false);
p3l8.setVisible(false);
p3l9.setVisible(false);
p3l10.setVisible(false);
p3l11.setVisible(false);
p3l12.setVisible(false);
p3l13.setVisible(false);
p3b3.setVisible(false);
p3l8.setVisible(true);
p3b4.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_p3b3ActionPerformed

    private void p3b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3b1ActionPerformed
String z=p3t1.getText();
int x=Integer.valueOf(z);


        if(p3t1.getText().isEmpty())
{JOptionPane.showMessageDialog(null, "plese enter id");
}else{
p3t1.setVisible(false);
p3l11.setText(str);
Calendar cal=Calendar.getInstance();
int h1=cal.get(Calendar.HOUR);
        int m1=cal.get(Calendar.MINUTE);
        int s1=cal.get(Calendar.SECOND);
        String o=String.valueOf(h1);
        String p=String.valueOf(m1);
        String q=String.valueOf(s1);
str1=(h1+":"+m1+":"+s1);
       try
   {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
  Connection con=DriverManager.getConnection("jdbc:odbc:tushar");
  Statement st=con.createStatement();
  
  int y=st.executeUpdate("update parking set Time_of_exit='"+str1+"',hour_of_exit='"+h1+"',min_of_exit='"+m1+"' where Pid='"+p3t1.getText()+"'");
   }catch(Exception e)
   {System.err.println(e);}

 
try
   {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
  Connection con=DriverManager.getConnection("jdbc:odbc:tushar");
  Statement st=con.createStatement();
  
  int y=st.executeUpdate("update parking set Time_of_exit='"+str1+"' where Pid='"+p3t1.getText()+"'");
   }catch(Exception e)
   {System.err.println(e);}
p3l12.setText(str1);
p3b2.setVisible(false);
p3l2.setVisible(false);
p3b1.setVisible(false);
p3b1.setVisible(false);
    try
   {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
  Connection con=DriverManager.getConnection("jdbc:odbc:tushar");
  Statement st=con.createStatement();
  
  ResultSet res=st.executeQuery("select * from parking where Pid="+x+"");
  while(res.next())
  {
int hh=res.getInt(6);
int mm=res.getInt(7);
int h2=res.getInt(8);
int m2=res.getInt(9);
int c1,c2,c3;
c1=(h2-hh)*60;
c2=(m2-mm);
c3=c2+c1;
String cs=String.valueOf(c3);
p3l13.setText(cs);
  }
   }catch(Exception j)
   {System.err.println(j);}
   

            try
   {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
  Connection con=DriverManager.getConnection("jdbc:odbc:tushar");
  Statement st=con.createStatement();
  
  ResultSet res=st.executeQuery("select * from parking where Pid="+x+"");
  while(res.next())
  {
p3l9.setText(res.getString(2));
p3l10.setText(res.getString(3));
p3l11.setText(res.getString(4));
p3l12.setText(res.getString(5));
 

  }
   }catch(Exception j)
   {System.err.println(j);}
               try
   {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
  Connection con=DriverManager.getConnection("jdbc:odbc:tushar");
  Statement st=con.createStatement();
  
  int y=st.executeUpdate("update parking set cost='"+p3l13.getText()+"' where Pid='"+p3t1.getText()+"'");
   }catch(Exception e)
   {System.err.println(e);}
p3l3.setVisible(true);
p3l4.setVisible(true);
p3l5.setVisible(true);
p3l6.setVisible(true);
p3l7.setVisible(true);
p3l9.setVisible(true);
p3l10.setVisible(true);
p3l11.setVisible(true);
p3l12.setVisible(true);
p3l13.setVisible(true);
p3b3.setVisible(true);
p3b5.setVisible(true);}
// TODO add your handling code here:
    }//GEN-LAST:event_p3b1ActionPerformed

    private void p3b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3b4ActionPerformed
p3.setVisible(false);
p1.setVisible(true);
p3l1.setVisible(true);
p3t1.setVisible(true);
p3b2.setVisible(true);
p3l2.setVisible(true);
p3b1.setVisible(true);
p3b1.setVisible(true);
p3l3.setVisible(true);
p3l4.setVisible(true);
p3l5.setVisible(true);
p3l6.setVisible(true);
p3l7.setVisible(true);
p3l9.setVisible(true);
p3l10.setVisible(true);
p3l11.setVisible(true);
p3l12.setVisible(true);
p3l13.setVisible(true);
p3b3.setVisible(true);
p3b5.setVisible(true);
p3b4.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_p3b4ActionPerformed

    private void p3b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3b5ActionPerformed
if(p3t1.getText().isEmpty())
{JOptionPane.showMessageDialog(null, "plese enter id");
}else{    p3t1.setVisible(true);
    p3b2.setVisible(true);
p3l2.setVisible(true);
p3b1.setVisible(true);
p3b1.setVisible(true);
p3l3.setVisible(false);
p3l4.setVisible(false);
p3l5.setVisible(false);
p3l6.setVisible(false);
p3l7.setVisible(false);
p3l9.setVisible(false);
p3l10.setVisible(false);
p3l11.setVisible(false);
p3l12.setVisible(false);
p3l13.setVisible(false);
p3b3.setVisible(false);
p3b5.setVisible(false);}    // TODO add your handling code here:
    }//GEN-LAST:event_p3b5ActionPerformed

    private void p4b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4b4ActionPerformed
if(p4t1.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "plese enter user");}
else if(p4p1.getText().isEmpty())
{
    JOptionPane.showMessageDialog(null, "plese enter password");
}
else{if(p4t1.getText().equals("harsh")){
            
if(p4p1.getText().equals("1234"))
{
 p4l2.setVisible(false);
p4l3.setVisible(false);
p4t1.setVisible(false);
p4p1.setVisible(false);
p4b3.setVisible(false);
p4b4.setVisible(false);
p4b1.setVisible(true);
p4b2.setVisible(true);
}else{JOptionPane.showMessageDialog(null, "incorrect password");}}else{
    JOptionPane.showMessageDialog(null, "incorrect user ");
}}// TODO add your handling code here:
    }//GEN-LAST:event_p4b4ActionPerformed

    private void p4b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4b2ActionPerformed
    p4l2.setVisible(true);
    p4t1.setText("");
    p4p1.setText("");
p4l3.setVisible(true);
p4t1.setVisible(true);
p4p1.setVisible(true);
p4b3.setVisible(true);
p4b4.setVisible(true);
p4b1.setVisible(false);
p4b2.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_p4b2ActionPerformed

    private void p2b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2b1ActionPerformed
if(p2t1.getText().isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please Enter Name");
}else if(p2t2.getText().isEmpty())
    {
        JOptionPane.showMessageDialog(null, "Please Enter Vehicle Number");
    }
else{
            p2t1.setVisible(false);
    p2b2.setVisible(false);
p2b1.setVisible(false);
p2t2.setVisible(false);
p2l7.setVisible(true);
p2l8.setVisible(true);
p2l9.setVisible(true);
p2l7.setText(p2t1.getText());
p2l8.setText(p2t2.getText());
p2b3.setVisible(true);
p2b4.setVisible(true);
p2l4.setVisible(true);
Calendar cal=Calendar.getInstance();
ho=cal.get(Calendar.HOUR);
mi=cal.get(Calendar.MINUTE);
 int s=cal.get(Calendar.SECOND);
 String str=String.valueOf(ho);
 String str1=String.valueOf(mi);
 String str2=String.valueOf(s);
p2l9.setText(str+":"+str1+":"+str2);
        

}// TODO add your handling code here:
    }//GEN-LAST:event_p2b1ActionPerformed

    private void p2b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2b3ActionPerformed
              try
   {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
  Connection con=DriverManager.getConnection("jdbc:odbc:tushar");
  Statement st=con.createStatement();
  ResultSet res=st.executeQuery("select top 1 Pid from parking order by Pid desc");
  while(res.next())
  {
     id=res.getInt("Pid");
      System.out.println(id);
 

  }
   }catch(Exception e)
   {System.err.println(e);}
                        id=id+1;
String r=String.valueOf(id);
p2l6.setText(r);
             try
   {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
  Connection con=DriverManager.getConnection("jdbc:odbc:tushar");
  Statement st=con.createStatement();
     
     
      int u=st.executeUpdate("insert into parking(Pid,Name,Vehicle_No,Time_of_entry,hour_of_entry,min_of_entry) values('"+p2l6.getText()+"','"+p2l7.getText()+"','"+p2l8.getText()+"','"+p2l9.getText()+"','"+ho+"','"+mi+"')");
 


   }catch(Exception e)
   {System.err.println(e);
   e.printStackTrace();}
p2l5.setVisible(true);
p2l1.setVisible(false);
p2b4.setVisible(false);
p2b3.setVisible(false);
p2l4.setVisible(false);
p2l6.setVisible(true);
p2l2.setVisible(false);
p2l3.setVisible(false);
p2l7.setVisible(false);
p2l8.setVisible(false);
p2l9.setVisible(false);
p2b5.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_p2b3ActionPerformed

    private void p2b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2b4ActionPerformed
p2t1.setVisible(true);
p2t2.setVisible(true);
        if(p2t1.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "Please Enter Name");}
        else if(p2t2.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Please Enter Vehicle Number");}
else{
        p2l7.setVisible(false);
p2b3.setVisible(false);
p2b4.setVisible(false);
p2b2.setVisible(true);
p2b1.setVisible(true);
p2l8.setVisible(false);
p2l9.setVisible(false);
p2l4.setVisible(false);
}// TODO add your handling code here:
    }//GEN-LAST:event_p2b4ActionPerformed

    private void p2b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2b5ActionPerformed
p2.setVisible(false);
p2l1.setVisible(true);
p2b1.setVisible(true);
p2b2.setVisible(true);
p2l2.setVisible(true);
p2b4.setVisible(false);
p2b3.setVisible(false);
p2l4.setVisible(true);
p2l5.setVisible(true);
p2l6.setVisible(true);
p2l3.setVisible(true);
p2l7.setVisible(true);
p2t1.setText("");
p2t2.setText("");
p2l8.setVisible(true);
p2l9.setVisible(true);
p2t1.setVisible(true);
p2t2.setVisible(true);
p2b5.setVisible(true);
p1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_p2b5ActionPerformed

    private void p4b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4b1ActionPerformed
p4.setVisible(false);
        p5.setVisible(true);
        try
   {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
  Connection con=DriverManager.getConnection("jdbc:odbc:tushar");
  Statement st=con.createStatement();
     ResultSet res=st.executeQuery("select * from parking");
     while(res.next())
     {Object o[]={res.getInt(1),res.getString(2),res.getInt(3),res.getString(4),res.getString(5),res.getInt(6),res.getInt(7),res.getInt(8),res.getInt(9),res.getInt(10)};
     tm.addRow(o);
jt1.setModel(tm);
     }
   }catch(Exception e)
   {
       System.out.println(e);
   }   // TODO add your handling code here:
    }//GEN-LAST:event_p4b1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
p4.setVisible(true);
p5.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parking_facility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parking_facility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parking_facility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parking_facility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parking_facility().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt1;
    private javax.swing.JLayeredPane p1;
    private javax.swing.JButton p1b1;
    private javax.swing.JButton p1b2;
    private javax.swing.JButton p1b3;
    private javax.swing.JLabel p1l1;
    private javax.swing.JLabel p1l2;
    private javax.swing.JLayeredPane p2;
    private javax.swing.JButton p2b1;
    private javax.swing.JButton p2b2;
    private javax.swing.JButton p2b3;
    private javax.swing.JButton p2b4;
    private javax.swing.JButton p2b5;
    private javax.swing.JLabel p2l1;
    private javax.swing.JLabel p2l2;
    private javax.swing.JLabel p2l3;
    private javax.swing.JLabel p2l4;
    private javax.swing.JLabel p2l5;
    private javax.swing.JLabel p2l6;
    private javax.swing.JLabel p2l7;
    private javax.swing.JLabel p2l8;
    private javax.swing.JLabel p2l9;
    private javax.swing.JTextField p2t1;
    private javax.swing.JTextField p2t2;
    private javax.swing.JLayeredPane p3;
    private javax.swing.JButton p3b1;
    private javax.swing.JButton p3b2;
    private javax.swing.JButton p3b3;
    private javax.swing.JButton p3b4;
    private javax.swing.JButton p3b5;
    private javax.swing.JLabel p3l1;
    private javax.swing.JLabel p3l10;
    private javax.swing.JLabel p3l11;
    private javax.swing.JLabel p3l12;
    private javax.swing.JLabel p3l13;
    private javax.swing.JLabel p3l2;
    private javax.swing.JLabel p3l3;
    private javax.swing.JLabel p3l4;
    private javax.swing.JLabel p3l5;
    private javax.swing.JLabel p3l6;
    private javax.swing.JLabel p3l7;
    private javax.swing.JLabel p3l8;
    private javax.swing.JLabel p3l9;
    private javax.swing.JTextField p3t1;
    private javax.swing.JLayeredPane p4;
    private javax.swing.JButton p4b1;
    private javax.swing.JButton p4b2;
    private javax.swing.JButton p4b3;
    private javax.swing.JButton p4b4;
    private javax.swing.JLabel p4l1;
    private javax.swing.JLabel p4l2;
    private javax.swing.JLabel p4l3;
    private javax.swing.JPasswordField p4p1;
    private javax.swing.JTextField p4t1;
    private javax.swing.JLayeredPane p5;
    // End of variables declaration//GEN-END:variables
}
